// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7jFk8xpDuc-nnKYYVo42BtXrSl2vdZ2w',
    appId: '1:946806169240:web:bfb5f2e3ee5a8865f23aed',
    messagingSenderId: '946806169240',
    projectId: 'swift-handler-224720',
    authDomain: 'swift-handler-224720.firebaseapp.com',
    databaseURL: 'https://swift-handler-224720.firebaseio.com',
    storageBucket: 'swift-handler-224720.firebasestorage.app',
    measurementId: 'G-9D158TKNPT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTlCKa_YWvctaQ0fvPs9dAw47k4xF1ae4',
    appId: '1:946806169240:android:8adb16d1cf7ace11f23aed',
    messagingSenderId: '946806169240',
    projectId: 'swift-handler-224720',
    databaseURL: 'https://swift-handler-224720.firebaseio.com',
    storageBucket: 'swift-handler-224720.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4NzxXb_Y1DO_WndDLoz9dALQyzF1xR44',
    appId: '1:946806169240:ios:0b0c24bf284f102af23aed',
    messagingSenderId: '946806169240',
    projectId: 'swift-handler-224720',
    databaseURL: 'https://swift-handler-224720.firebaseio.com',
    storageBucket: 'swift-handler-224720.firebasestorage.app',
    iosBundleId: 'com.jeremyfernandez.pushApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC4NzxXb_Y1DO_WndDLoz9dALQyzF1xR44',
    appId: '1:946806169240:ios:0b0c24bf284f102af23aed',
    messagingSenderId: '946806169240',
    projectId: 'swift-handler-224720',
    databaseURL: 'https://swift-handler-224720.firebaseio.com',
    storageBucket: 'swift-handler-224720.firebasestorage.app',
    iosBundleId: 'com.jeremyfernandez.pushApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA7jFk8xpDuc-nnKYYVo42BtXrSl2vdZ2w',
    appId: '1:946806169240:web:477a729aac89724bf23aed',
    messagingSenderId: '946806169240',
    projectId: 'swift-handler-224720',
    authDomain: 'swift-handler-224720.firebaseapp.com',
    databaseURL: 'https://swift-handler-224720.firebaseio.com',
    storageBucket: 'swift-handler-224720.firebasestorage.app',
    measurementId: 'G-12PCFE4MBL',
  );
}
